### ISSUE TITLE
同步结果总是智能跳过

### ISSUE THREAD

**Issue by h1048576** [qiniu/QSunSync#18]
用这个工具同步，第一次同步成功了，然后我手动删除了，后续同步就一直提示智能跳过，但是在七牛上是搜不到文件的。

**Comment by jemygraw** [comment]
因为同步成功之后，本地会记录下任务的同步情况，如果你空间删除，然后希望能再次同步本地文件的话，可以在首页里的任务列表删除那个任务，重新建立一次。

**Comment by fengyhack** [comment]
请参考[使用手册](http://oiy037d6a.bkt.clouddn.com/qsunsync-man-v1.7.0/index.html)，检查是否勾选了【增量同步】选项：
![LocalIncrement](http://oiy037d6a.bkt.clouddn.com/qsunsync-man-v1.7.0/imgs/3-05-1.png)

**Comment by xbuilder** [comment]
![image](https://cloud.githubusercontent.com/assets/10357081/23356345/71852eea-fd14-11e6-9944-c7fcac7a0c48.png)
@fengyhack 果然和我 猜想的一样，没空间的时候，空引用了
