### ISSUE TITLE
1.9.1 点新建同步任务，程序崩溃

### ISSUE THREAD

**Issue by LyricsYo** [qiniu/QSunSync#22]
![default](https://cloud.githubusercontent.com/assets/10357081/23352050/eb198a54-fcff-11e6-9d99-2e3dd8151234.png)
@fengyhack 如图

**Comment by LyricsYo** [comment]
初步推断是因为账号下没有空间导致的，一会源码调试下看看

另外还有一个bug， 第一次设置账号是没生效的（切换账号也是），要两次才行

**Comment by fengyhack** [comment]
@xbuilder 
感谢反馈。

1.程序异常终止的原因暂不确定。我们会继续排查（如果能提供反馈或协助会更好），查明问题后会尽快修复。

在C# SDK 7.2.11及以前的版本里面存在一个隐秘的bug（也不算是bug），此bug可能会导致（引用此SDK计算MD5）的程序异常终止。

这个“隐秘的bug”是：
SDK中计算MD5哈希会调用到`System.Security.Cryptography.MD5`，如果本机注册表项
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy
设置为1则会抛出异常，设置为0则没有问题。
在7.2.12+版本已增加第三方MD5算法(`LabMD5`)以避免这个问题。

2.设置账号的问题，我们这边测试一下，查明问题后会尽快修复。

**Comment by LyricsYo** [comment]
![image](https://cloud.githubusercontent.com/assets/10357081/23356399/9b909dd2-fd14-11e6-9bb5-a8fdb1ff9fa7.png)
@fengyhack 果然和我 猜想的一样，获取空间列表的时候空引用了

**Comment by fengyhack** [comment]
@xbuilder 
非常感谢。
看来第一个问题可以确定了，后续更新会修复此问题，解决后的效果可能是：当buckets为空的时候，在界面上给出适当提示。
