### ISSUE TITLE
1.9.1 需要分片上传的文件，全部同步失败

### ISSUE THREAD

**Issue by LyricsYo** [qiniu/QSunSync#23]
@fengyhack 这两天在同步数据到七牛云了，这个问题有点急，麻烦看下（确定不是网络原因造成的）

**Comment by fengyhack** [comment]
可否提供一下使用环境（比如Win10 x64等）以及同步工具的日志？
其中，日志文件在【文档】【qsunsync】文件夹下，文件名为sync.log

**Comment by LyricsYo** [comment]
@fengyhack 这个日志是db文件，这上传不了，给我一个邮箱地址吧,
我看了下没上传成功的都是大于4MB的文件（设置的分片大小是4MB），环境是windows server 2016  x64
发现问题后，又在win10 x64的环境下用一个文件夹放了一个大于4MB的文件进行同步，结果也是一样同步不上去

**Comment by LyricsYo** [comment]
那个日志是sqlite文件，我看了下，里面也是只有key,loacl_path,last_modified 三个字段的数据。。貌似没有什么可供参考的数据

**Comment by LyricsYo** [comment]
@fengyhack 这个问题已经定位了，上传的时候选择 "CDN加速" ，在进行分片上传的时候就会上传失败，错误信息如下 
![image](https://cloud.githubusercontent.com/assets/10357081/23393685/86e03c98-fdbf-11e6-99eb-1273a86386ef.png)

选择直传则不会出问题

**Comment by fengyhack** [comment]
@xbuilder 
日志文件就在 文档\qsunsync 文件夹下，文件名为sync.log（扩展名可能能隐藏了），如果能找到的话，不妨打开看一下。

这个上传失败问题的原因可能是：
使用“CDN加速”上传时，上传数据块后返回的消息内容(包含JSON数据)不完整（或者接收不完整）

为了定位问题并修复，可否提供一下抓包内容？
非常感谢。

**Comment by LyricsYo** [comment]
@fengyhack 
![image](https://cloud.githubusercontent.com/assets/10357081/23452083/d5816bcc-fe9d-11e6-9e4c-669c9630345f.png)
用fiddler抓包的时候弹出了这个提示
![image](https://cloud.githubusercontent.com/assets/10357081/23452164/3c10e71e-fe9e-11e6-9c15-453d538e1ab9.png)
程序里的RefText
![image](https://cloud.githubusercontent.com/assets/10357081/23452346/f5952196-fe9e-11e6-9275-058e7bdaa54e.png)
同步日志

**Comment by fengyhack** [comment]
抓包提示body内容344字节，但实际收到的只有287字节
这个应该是使用"CDN上传"时才可能出现的问题
如果此问题再次出现，使用“直传”即可。

**Comment by LyricsYo** [comment]
@fengyhack 嗯是的，目前就是用的 直传 模式了
