### ISSUE TITLE
为什么我没有找到可执行的程序？exe文件在哪里？或者那个是程序的执行入口文件？

### ISSUE THREAD

**Issue by renjianfeng** [qiniu/QSunSync#27]
我不会编译，该程序有没有编译后的版本？

**Comment by fengyhack** [comment]
@renjianfeng 
直接看项目主页[https://github.com/qiniu/QSunSync](https://github.com/qiniu/QSunSync)，README里面就给了下载链接

最新版本下载 [QSunSync-v1.10.1](http://devtools.qiniu.com/QSunSync-v1.10.1.zip)
使用手册请戳这里 [在线浏览](http://oiy037d6a.bkt.clouddn.com/qsunsync-man-v1.7.0/index.html)
