### ISSUE TITLE
任务一开始同步就停止任务,这个是电脑问题吗?

### ISSUE THREAD

**Issue by zhougonglai** [qiniu/QSunSync#32]
![qq 20170508051709](https://cloud.githubusercontent.com/assets/10954751/25785218/aaef966e-33ad-11e7-8a24-f374e0b7e6a7.png)

**Comment by jemygraw** [comment]
这个看看是否按照了sqlite库。

**Comment by jemygraw** [comment]
可以试试最新v2.0.0
