### ISSUE TITLE
windows版上传全路径

### ISSUE THREAD

**Issue by linwoain** [qiniu/QSunSync#34]
![feedback](http://7xniib.com1.z0.glb.clouddn.com/qiniufeedback.jpg)

同一个文件夹，有的会传上去windows全路径，网页版上看到的确实是有全路径。

**Comment by jemygraw** [comment]
这个你找找看这个文件的实际路径在哪里。

**Comment by jemygraw** [comment]
这个问题暂时不知道如何复现，关闭。
