### ISSUE TITLE
同步进度条上面的显示与总上传进度不符合

### ISSUE THREAD

**Issue by Zheng-Caeser** [qiniu/QSunSync#36]
同步进度条上面的显示与总上传进度不符合

总上传进度显示上传成功比如13/30
同步进度条指显示几条文件
![image](https://user-images.githubusercontent.com/10324535/27681680-a4181c8a-5cf2-11e7-9d11-d7b6b80ab449.png)

**Comment by jemygraw** [comment]
进度表里面只显示当前在传的文件，这个数量<=设置的并发数
