### ISSUE TITLE
win 10 打开就崩溃

### ISSUE THREAD

**Issue by w550** [qiniu/QSunSync#39]
![1](https://user-images.githubusercontent.com/11831434/28007436-fd5e3db0-6585-11e7-8a65-99d70035bc6f.png)
![2](https://user-images.githubusercontent.com/11831434/28007439-0015dc84-6586-11e7-904c-5e2d66442ceb.png)
![3](https://user-images.githubusercontent.com/11831434/28007441-018132bc-6586-11e7-8dd2-cf03d43b9e05.png)
![4](https://user-images.githubusercontent.com/11831434/28007445-02ed14a4-6586-11e7-9019-266a1502fc0c.png)
![5](https://user-images.githubusercontent.com/11831434/28007447-04cf4580-6586-11e7-82c8-b081311f2502.png)

**Comment by angilent** [comment]
如果本地同步目录为空，也遇到类似问题。

**Comment by jemygraw** [comment]
可以试试2.0.0版本，已在windows 10下面测试
