### ISSUE TITLE
“PutPolicy”未包含“FileType”的定义，并且找不到可接受第一个“PutPolicy”类型参数的扩展方法“FileType”

### ISSUE THREAD

**Issue by suecher** [qiniu/QSunSync#40]
下载的最新版本源码，Qiniu.DLL 加载的是 根目录下 packages/Qiniu.Shared.7.2.14/net40/ 但是提示PutPolicy 中FileType 没有定义.请问这是什么问题？是否我引用错误？

**Comment by jemygraw** [comment]
sdk和工具的问题这周修复，抱歉

**Comment by suecher** [comment]
好的。。非常感谢。

**Comment by jemygraw** [comment]
https://github.com/qiniu/csharp-sdk 最新版7.0.3已修复问题，目前本项目已同步更新。
