### ISSUE TITLE
体验不好,多个问题还需改善

### ISSUE THREAD

**Issue by cloverzrg** [qiniu/QSunSync#43]
大量小文件同步慢,不能满速同步
同步失败的文件不能方便地重试同步

**Comment by cloverzrg** [comment]
另外,为什么所有的进度都100%了还要等待十秒左右才开始新的上传队列,上传只要两秒啊

**Comment by jemygraw** [comment]
文件比较多的，用 https://github.com/qiniu/qshell  中的qupload上传。
