### ISSUE TITLE
不管我放什么进去同步的时候都是0

### ISSUE THREAD

**Issue by houko** [qiniu/QSunSync#44]
![image](https://user-images.githubusercontent.com/12625278/30259323-3de3f548-96f3-11e7-9c46-eeb292c19f12.png)
![image](https://user-images.githubusercontent.com/12625278/30259326-4483252c-96f3-11e7-8b35-6b1a39b0b2cf.png)

**Comment by jemygraw** [comment]
你“高级设置”里面选中”检查本地文件更新“选项

**Comment by houko** [comment]
thanks
