### ISSUE TITLE
v2.1 怎么上传大文件

### ISSUE THREAD

**Issue by lhwu** [qiniu/QSunSync#45]
1、上传时，上传速度90k/s，平时下载速度1.5M/s，怎么提高上传速度。在网页上传4m的小视频也才4s左右
2、上传老实失败，失败的日志还没有原因
求解

**Comment by jemygraw** [comment]
你的网络太差了，没别的原因。

**Comment by lhwu** [comment]
qshell 上传速度1M，qSync没成功过，差距还是有的

**Comment by jemygraw** [comment]
没有成功的话，看看日志导出可以提供下
