### ISSUE TITLE
也太烂了把，加文件加不了

### ISSUE THREAD

**Issue by callmesoul** [qiniu/QSunSync#47]
同步完一次，然后想里面加入文件。压根就没检查到新文件。就是每次同步都没上传新文件

**Comment by jemygraw** [comment]
你把高级设置里面的，“检查本地新增文件” 勾选上。
如果成功了，麻烦你把标题改下。

**Comment by callmesoul** [comment]
真的不行，完全检测不了有新文件

**Comment by jemygraw** [comment]
那说明你本地没有新的文件。
