### ISSUE TITLE
遇到空间中存在同名文件则强制覆盖不可用

### ISSUE THREAD

**Issue by wuliwuwai** [qiniu/QSunSync#51]
在空间有相同文件的情况下，勾选了【遇到空间中存在同名文件则强制覆盖】，也没有强制覆盖更新。而检测文件的hash值，只有文件名相同，hash值不同的时候才会更新。这样设计的话，想变更文件的存储模式也没有办法了

**Comment by jemygraw** [comment]
存储模式不可以通过覆盖的方式来更新。如果需要修改存储类型，可以使用[qshell](https://github.com/qiniu/qshell)的chtype或者batchchtype功能来实现。
