### ISSUE TITLE
win10  有非常大的假死纪律

### ISSUE THREAD

**Issue by vsxen** [qiniu/QSunSync#7]
选择空间的时候，多点击一下必定假死，点一下也会死（有时候
会提示服务连接失败啊  操作超时啊）
![qiniu](https://cloud.githubusercontent.com/assets/8838032/18841275/c1d08d08-8443-11e6-97cc-970be2a261d8.png)

**Comment by longbai** [comment]
我们看下

**Comment by fengyhack** [comment]
已经在出现问题的部分做了优化。
在多次测试中并未出现此问题，但根据次反馈，仍然进行了一些优化。
更新版本中已包含此项优化。
